# Project 9

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/home/ramseyc/Downloads/ufo2.csv')

In [3]:
df.head()

,Date,City,State,Country,Shape of UFO
0,4/8/23 19:30,Brighton/Fairfield,IA,USA,Teardrop
1,4/8/23 18:45,Ocean Shores,New South Wales,Australia,Triangle
2,4/8/23 05:39,Southampton,MA,USA,Light
3,4/7/23 22:15,ST BRUNO DE MONTARVILLE,Quebec,Canada,Changing
4,4/7/23 21:55,Bedford,VA,USA,Cube

In [4]:
df['Place'] = df['City'] + ', ' + df['State']

In [5]:
df.head()

,Date,City,State,Country,Shape of UFO,Place
0,4/8/23 19:30,Brighton/Fairfield,IA,USA,Teardrop,"Brighton/Fairfield, IA"
1,4/8/23 18:45,Ocean Shores,New South Wales,Australia,Triangle,"Ocean Shores, New South Wales"
2,4/8/23 05:39,Southampton,MA,USA,Light,"Southampton, MA"
3,4/7/23 22:15,ST BRUNO DE MONTARVILLE,Quebec,Canada,Changing,"ST BRUNO DE MONTARVILLE, Quebec"
4,4/7/23 21:55,Bedford,VA,USA,Cube,"Bedford, VA"

In [10]:
df = df[df['Country'] == 'USA']
df.head()

,Date,City,State,Country,Shape of UFO,Place
0,4/8/23 19:30,Brighton/Fairfield,IA,USA,Teardrop,"Brighton/Fairfield, IA"
2,4/8/23 05:39,Southampton,MA,USA,Light,"Southampton, MA"
4,4/7/23 21:55,Bedford,VA,USA,Cube,"Bedford, VA"
5,4/7/23 18:35,Scottsdale,AZ,USA,Unknown,"Scottsdale, AZ"
6,4/7/23 08:40,St. Louis,MO,USA,Unknown,"St. Louis, MO"

In [11]:
from geopy.exc import GeocoderTimedOut
from geopy.geocoders import Nominatim
   
# declare an empty list to store
# latitude and longitude of values 
# of city column
longitude = []
latitude = []
   
# function to find the coordinate
# of a given city 
def findGeocode(city):
       
    # try and catch is used to overcome
    # the exception thrown by geolocator
    # using geocodertimedout  
    try:
          
        # Specify the user_agent as your
        # app name it should not be none
        geolocator = Nominatim(user_agent="your_app_name")
          
        return geolocator.geocode(city)
      
    except GeocoderTimedOut:
          
        return findGeocode(city)    
  
# each value from city column
# will be fetched and sent to
# function find_geocode   
for i in (df["City"]):
      
    if findGeocode(i) != None:
           
        loc = findGeocode(i)
          
        # coordinates returned from 
        # function is stored into
        # two separate list
        latitude.append(loc.latitude)
        longitude.append(loc.longitude)
       
    # if coordinate for a city not
    # found, insert "NaN" indicating 
    # missing value 
    else:
        latitude.append(np.nan)
        longitude.append(np.nan)

GeocoderServiceError: Non-successful status code 502

In [12]:
import requests

def find_geocode(address):
    url = f'https://maps.googleapis.com/maps/api/geocode/json?address={address}&key=YOUR_API_KEY'
    response = requests.get(url)
    if response.status_code == 200:
        location = response.json()['results'][0]['geometry']['location']
        return location['lat'], location['lng']
    else:
        print(f"Error: {response.status_code}")
        return None

find_geocode("New York City")

IndexError: list index out of range